server:
  port: 8089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

jwt:
  token:
    pubKeyPath: E:\gmall-0805\rsa\rsa.pub # 公钥地址
    priKeyPath: E:\gmall-0805\rsa\rsa.pri # 私钥地址
    secret: sf3423jsdf#3$@FDS32
    expire: 30 # 过期时间,单位分钟
    cookieName: GMALL_TOKEN